neptune: neptune.cpp bitboard.cpp board.cpp brain.cpp evaluation.cpp movegen.cpp slidingattack.cpp transposition.cpp zobrist.cpp
	g++ -std=c++17 -Wall -O3 -o neptune neptune.cpp bitboard.cpp board.cpp brain.cpp evaluation.cpp movegen.cpp slidingattack.cpp transposition.cpp zobrist.cpp
